version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"   # REST API
      - "6334:6334"   # gRPC (opcional)
    volumes:
      - ${DATA_PATH}:/qdrant/storage
    restart: unless-stopped
